# Generated by Django 2.2.7 on 2019-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('actual_file_name', models.CharField(max_length=200)),
                ('process_file_name', models.CharField(max_length=200)),
                ('queue_id', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'In progress'), (2, 'Completed')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
