# Generated by Django 2.2.7 on 2019-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='folder_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
